services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - tbdata:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432

volumes:
  tbdata: